name : Terraform CICD pipeline to deploy to AWS resources
run-name: ${github.actor}} has triggered the pipeline

on:
  push:
    branches:
      - main
  
env:
  AWS_REGION: us-east-1
  TF_VAR_region: us-east-1
  TF_VAR_aws_access_key_id: ${{ secrets.ACCESS_KEY_ID }}
  TF_VAR_aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: terraform-cicd-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./Terraform-VPC

      - name: Terraform Plan
        id: plan
        working-directory: ./Terraform-VPC
        run: terraform plan

      - name: Terraform Apply
        id: apply
        working-directory: ./Terraform-VPC
        run: terraform apply -auto-approve
